[package]
name = "rusty"
version = "0.1.0"
authors = ["Stephen Dolan <stephen.dolan@cl.cam.ac.uk>, Sophia Gold <sophiagoldnyc@gmail.com>"]

[dependencies]
dmz = { path = '../core' }

[lib]
name = "rusty"
crate-type = ["staticlib"]
