[package]
name = "dmz"
version = "0.3.0"
authors = ["Stephen Dolan <stephen.dolan@cl.cam.ac.uk>, Sophia Gold <sophiagoldnyc@gmail.com>"]

[dependencies]
libc = "0.2.0"
derive_mltype = { path = "./derive_mltype" }

[lib]
name = "dmz"
crate-type = ["rlib"]

