external tostring : (string * int) -> string = "tostring"
external mkpair : 'a -> 'b -> ('a * 'b) = "mkpair"
external strtail : string -> string option = "strtail"
external somestr : int -> string option = "somestr"
external triple : 'a -> ('a * ('a * 'a)) = "triple"
external bigstrtail : Bigstring.t -> Bigstring.t option = "bigstrtail"
